package hu.bme.aut.wman.model;

public enum HistoryEntryEventType {
	COMMENTED,
	UPLOADED_FILE,
	ASSIGNED_USER,
	UNASSIGNED_USER,
	EDITED_PROJECT,
	CLOSED_PROJECT,
	REOPENED_PROJECT,
	DOWNLOADED_FILE,
	REMOVED_FILE,
	DONE_ACTION;
}
